[workspace]
members = [
    "clickhouse-data-type",
    "clickhouse-data-value",
    "clickhouse-format",
    "clickhouse-http-client",
    "clickhouse-postgres-client",
    "demos/postgres_client",
    "demos/http_client",
    "sqlx-clickhouse-ext",
]
resolver = "2"
